[build-system]
requires = ["setuptools>=45", "wheel"]
build-bakcend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--ignore-glob=lib/*"
markers = [
    "skip_if_no_connection: skips the test if there is no connection to the OCB",
]